### ISSUE TITLE
Formatter breaks T-SQL

### ISSUE THREAD

**Issue by bowmanjd** [nanotee/sqls.nvim#15]
The database connections work very well with Microsoft SQL Server. However, the formatter is unusable. Try formatting a query like `SELECT TOP 100 * FROM Table` and it doesn't seem to know what to do with `TOP`.

Is the answer just to disable the formatter in the lsp config, or are there other formatter configuration parameters I have missed?

**Comment by nanotee** [comment]
This plugin is only a wrapper around the `sqls` language server and does not handle formatting, I would suggest reporting this issue upstream: https://github.com/lighttiger2505/sqls/issues

**Comment by bowmanjd** [comment]
Ah, yes. My mistake. I will create an issue there. Thank you!
