### ISSUE TITLE
Commands are not recognized.

### ISSUE THREAD

**Issue by reiend** [nanotee/sqls.nvim#18]
I installed it using [minpac](https://github.com/k-takata/minpac)
I have config.yml for db and the Lsp was working fine.
but the editor can't seem recognized any of the commands provided.
I tried using [lighttiger2505/sqls.vim](https://github.com/lighttiger2505/sqls.vim), commands was there but it doesn't seem support nvim-lsp.

### OS
Windows 10

### Terminal
Powershell v7.2.2

### Editor
nvim v0.6.1

### Database
postgresql 13.6

**Comment by nanotee** [comment]
Are you calling this plugin's `on_attach()` function in your config?
```lua
require('lspconfig').sqls.setup{
    on_attach = function(client, bufnr)
        require('sqls').on_attach(client, bufnr)
    end
}
```

**Comment by reiend** [comment]
@nanotee thanks, you're on spot. close #18
