### ISSUE TITLE
Why do you keep supporting this project if sqls is archive?

### ISSUE THREAD

**Issue by D00mch** [nanotee/sqls.nvim#27]
https://github.com/lighttiger2505/sqls
![image](https://user-images.githubusercontent.com/14236531/227515451-82b43737-7c4b-46fb-a248-b936400ac000.png)

**Comment by nanotee** [comment]
The functionality of the language server remains useful even if the project is not maintained anymore, so I'm going to keep updating this plugin for the time being.
