### ISSUE TITLE
Error when running `:SqlsExecuteQuery` with by line visual selection

### ISSUE THREAD

**Issue by caenrique** [nanotee/sqls.nvim#3]
For some reason, when I select by line in visual mode (using capital v) and run `:SqlsExecuteQuery` it fails with the message:

> Error executing vim.schedule lua callback: ...m/site/pack/packer/start/sqls.nvim/lua/sqls/commands.lua:10: unexpected panic: runtime error: slice bounds out of range [:10] with length 9

But selecting by character in visual mode works fine.

**Comment by nanotee** [comment]
Thanks for the report, I've actually encountered this issue before. I'm unsure whether it's a problem with the language server or if I'm using `make_given_range_params()` incorrectly. I suspect there might be some weirdness going on with the `'selection'` option as well. I'll investigate.

**Comment by nanotee** [comment]
I made some changes in #4 that should fix this issue

**Comment by caenrique** [comment]
I haven't tried it yet, but I will when I get back to work. Thanks for your time!
