### ISSUE TITLE
Implement a show tables function

### ISSUE THREAD

**Issue by JacobDer** [nanotee/sqls.nvim#5]
First of all, I'm enjoying this plugin a lot—it's really neat! :)

I was thinking it might be cool to implement a command like `:SqlsShowTables` that will execute something like the query
```
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
AND table_type = 'BASE TABLE';
```
In order to ease working with databases where you may not have all of the table names memorized.

Or, is there another simple way to view table names that I  am missing?

**Comment by nanotee** [comment]
Thanks, glad you like the plugin! Though credit should go to `lighttiger2505` for creating the language server, this is only a simple wrapper around it

There's actually code for `:SqlsShowTables` in both `sqls.nvim` ([1](https://github.com/nanotee/sqls.nvim/blob/ade34622050a4a1a50b9db1229a0a60d64e69bdb/lua/sqls/init.lua#L16-L18)) and `sqls.vim` ([2](https://github.com/lighttiger2505/sqls.vim/blob/ca16e7b30d79ae566d1f40d4d808d36f0f1717a0/plugin/sqls.vim#L8-L9), [3](https://github.com/lighttiger2505/sqls.vim/blob/ca16e7b30d79ae566d1f40d4d808d36f0f1717a0/autoload/sqls.vim#L83-L89)), but as you can see the code action has yet to be implemented in `sqls` itself

**Comment by JacobDer** [comment]
Ahhh I see. That's a bummer, but hopefully that functionality will be added at some point! 

I'll go ahead and close this for now, and add a comment if I come up with a nice hack for this.
